### ISSUE TITLE
2.x: maven archetypes fail with maven 3.9.6

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon-build-tools#1031]
With maven 3.9.6 run

```
mvn -U archetype:generate -DinteractiveMode=false \
    -DarchetypeGroupId=io.helidon.archetypes \
    -DarchetypeArtifactId=helidon-quickstart-mp \
    -DarchetypeVersion=2.6.6 \
    -DgroupId=io.helidon.examples \
    -DartifactId=helidon-quickstart-mp \
    -Dpackage=io.helidon.examples.quickstart.mp
```

It fails with:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (default-cli) on project standalone-pom: 
Execution default-cli of goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate failed: 
A required class was missing while executing org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate: 
com/github/mustachejava/MustacheFactory
```

Stack from -X
```
Caused by: java.lang.ClassNotFoundException: com.github.mustachejava.MustacheFactory
    at java.net.URLClassLoader.findClass (URLClassLoader.java:471)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:588)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:521)
    at java.lang.Class.getDeclaredConstructors0 (Native Method)
    at java.lang.Class.privateGetDeclaredConstructors (Class.java:3137)
    at java.lang.Class.getConstructor0 (Class.java:3342)
    at java.lang.Class.getConstructor (Class.java:2151)
    at io.helidon.build.archetype.maven.postgenerate.EngineFacade.generate (EngineFacade.java:134)
```

If I run with maven 3.8.2 all is well.
If I run a Helidon 3.x archetype (with maven 3.9.6) all is well.

**Comment by romain-grecourt** [comment]
This is because the dependency resolution of `io.helidon.build-tools:helidon-archetype-engine:2.3.7` fails silently and we end-up with a class-loader with just one URL (the archetype-engine JAR file).

- The dependency resolution fails because the effective model resolution of `helidon-archetype-engine` fails
- `helidon-archetype-engine` inherits `helidon-build-tools-project` which imports `helidon-bom:0.9.0` which has a profile activated by a jdk version
- The active profile check fails because the aether repository session does not have system properties

```
org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model for io.helidon.build-tools.archetype:helidon-archetype-engine:2.3.7
[ERROR] Failed to determine Java version for profile jdk9+ @ io.helidon:helidon-project:0.9.0

	at org.apache.maven.model.building.DefaultModelProblemCollector.newModelBuildingException(DefaultModelProblemCollector.java:176)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:508)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:410)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:243)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:284)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:175)
	at org.eclipse.aether.internal.impl.collect.DependencyCollectorDelegate.collectDependencies(DependencyCollectorDelegate.java:179)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:87)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:328)
	at io.helidon.build.archetype.maven.postgenerate.Aether.resolveDependencies(Aether.java:221)
```
---

```
String version = context.getSystemProperties().get("java.version");

if (version == null || version.length() <= 0) {
    problems.add(new ModelProblemCollectorRequest(Severity.ERROR, Version.BASE)
            .setMessage("Failed to determine Java version for profile " + profile.getId())
            .setLocation(activation.getLocation("jdk")));
    return false;
}
```

**Comment by romain-grecourt** [comment]
This is caused by a changed my in Maven 3.9.0 in this [commit](https://github.com/apache/maven/commit/0f4387543debd77ab649f97014b72feb4046b3c6#diff-cb5d02757aeefc9ff0ed9d5a411cfcc575d2371557a290f209b97535c70ce2e9L132)

We use `MavenRepositorySystemUtils.newSession()` to create a new `RepositorySystemSession` and pre 3.9.0 the session had system properties populated.
