### ISSUE TITLE
VSCode - Cannot invoke "java.util.Set.stream()"

### ISSUE THREAD

**Issue by danielkec** [helidon-io/helidon-build-tools#869]
Exception when trying to get code complete in yaml conf of MP quickstart after `mp.`.

```
[Error - 3:52:10 PM] Request textDocument/completion failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "java.util.Set.stream()" because the return value of "io.helidon.lsp.server.management.MavenSupport.dependencies(String)" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Set.stream()" because the return value of "io.helidon.lsp.server.management.MavenSupport.dependencies(String)" is null
	at io.helidon.lsp.server.service.config.ConfigurationPropertiesService.metadataForPom(ConfigurationPropertiesService.java:126)
	at io.helidon.lsp.server.service.config.ConfigurationPropertiesService.metadataForFile(ConfigurationPropertiesService.java:557)
	at io.helidon.lsp.server.service.config.yaml.YamlTextDocumentHandler.completion(YamlTextDocumentHandler.java:96)
	at io.helidon.lsp.server.core.HelidonTextDocumentService.lambda$completion$0(HelidonTextDocumentService.java:135)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more

```

**Comment by aserkes** [comment]
Most probably that the problem is related to the maven plugin `helidon-lsp-maven-plugin`. The extension uses this plugin for code completion in config files. At the same time this plugin has not been published to the any maven repository yet, so if you do not have it locally such feature as code completion for config files will not work.
So, could you please check your local maven repository `~/.m2/repository/io/helidon/ide-support/lsp` does it contain `helidon-lsp-maven-plugin?
If this plugin is not installed locally I would like to propose you to download `helidon-build-project` and build it using `mvn clean install -DskipTests` or just build the `helidon-lsp-maven-plugin` module.
After performing this operation, the error should disappear.
